### ISSUE TITLE
Not really issue but comptability tweaks

### ISSUE THREAD

**Issue by Ghozgul** [Coderx-Gamer/shulker-dupe#43]
The mod is working great but I recently installed Inventory Tabs who allows to access all inventory surrounding the player, but the two GUI are overlapping, and even if the dupe button on top, clicking on it ignores it and clicks on the other mod tab.

Here is an image to explain: https://ibb.co/jMqTjSq

An option to move the GUI would be awesome, as well as an option to turn off the mod or hide the buttons. I often share my screen and I need to log off to turn off the mod to avoid getting caught :)

Great mod anyway !

**Comment by Coderx-Gamer** [comment]
Sorry about the mod not rendering the two screens correctly, I might add an option to move the buttons at some point, idk don't count on it lol, Try clicking the very top of the buttons that you showed in the screenshot. Also there is already an option to show/hide the buttons in the latest release, Make sure u have the latest release or it will probably get you caught because the command isn't added yet, Type "^toggleshulkerdupe" in the chat and it will show/hide the buttons.

**Comment by Ghozgul** [comment]
Unfortunately clicking on the very last pixel on top doesn't work, the clicking area of the other mod is wider than what the icon shows. But good to know that the option to hide it is there.
Would it be possible to only hide the button but without disabling the mod ? If we know where the buttons are, hiding them isn't a problem :P
